certificate/urls.py
from django.urls import path
from certificate.views import *

app_name = 'certificate'
urlpatterns = [
    path('create/', create, name='create'),
    path('<int:certificate_id>/', detail, name='detail'),
    path('<int:certificate_id>/accept', accept, name='accept'),
    path('<int:certificate_id>/delete', delete, name='delete'),
    path('lists/', lists, name='lists'),
    path('confirm_lists/', confirm_lists, name='confirm_lists'),
    path('cancle_lists/', cancle_lists, name='cancle_lists'),
    path('<int:certificate_id>/pdf', print_pdf, name='print_pdf'),
    path('<int:certificate_id>/downloadpdf', download_pdf, name='download_pdf'),

]

src/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('pages.urls')),
    path('admin/', admin.site.urls),
    path('certificate/', include('certificate.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <!-- AJAX -->
    <!-- JQuery CDN -->
    <script src="{% static 'javascript/jquery-3.4.1.min.js' %}"></script>

    <!-- FontAwesome CDN -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css" integrity="sha384-oS3vJWv+0UjzBfQzYUhtDYW+Pj2yciDJxpsK1OYPAYjqT085Qq/1cq5FLXAZQ7Ay" crossorigin="anonymous">

    <link href='{% static "main.css" %}' rel="stylesheet" media="screen">
    <title>PLX - POLIPOL</title>

</head>
<body>
    {% include "header.html" %}
    <div class="container">
        <br>
        {% if messages %}
                {% for message in messages %}
                    <div id="message" {% if message.tags %} class="alert alert-{{ message.tags }}"{% endif %}>{{ message }}</div>
                {% endfor %}
        {% endif %}
        {% block content %}

        {% endblock content %}
    </div>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    
    <!-- JS for copy button and AJAX search -->
    <script type="text/javascript" src='{% static "javascript/main.js" %}'></script>
    <script type="text/javascript" src='{% static "javascript/copy.js" %}'></script>
    <script>
    $(function() {
        setTimeout(function() { $("#message").fadeOut(1500); }, 4000)
    })
    </script>
</body>
</html>

src/templates/header.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="/"><b>LOGO</b></a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavDropdown">
    <ul class="navbar-nav">
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Statements
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
          <a class="dropdown-item" href="{% url 'certificate:lists' %}">All statements</a>
          <a class="dropdown-item" href="{% url 'certificate:confirm_lists' %}">Confirm statements</a>
          <a class="dropdown-item" href="{% url 'certificate:cancle_lists' %}">Cancle statements</a>
          <a style="font-weight:bold;" class="dropdown-item" href="{% url 'certificate:create' %}">Create statement</a>
        </div>
      </li>
    </ul>
  </div>
</nav>